(require 'cc-mode)

(define-key c-mode-base-map (kbd "RET") 'newline-and-indent)
(c-toggle-electric-state 1)
(c-toggle-hungry-state 1)

(defun hypirion-c-mode-insert-brackets ()
  (interactive)
  (let* ((pps (syntax-ppss))
         (original-pos (point))
         (last-char (prog2 (re-search-backward "^\\|[^[:space:]]")
                        (following-char)
                      (goto-char original-pos))))
    (insert "{")
    (when (and (eolp) (not (or (nth 3 pps) (nth 4 pps))))
      (when (/= last-char ?=)
        (c-indent-line)
        (insert "\n\n}")
        (c-indent-line)
        (forward-line -1)
        (c-indent-line)))))

(define-key c-mode-base-map "{" 'hypirion-c-mode-insert-brackets)

(provide 'hypirion-c)
